export enum UserPatientFamilyRelationship {
  MOTHER = 'madre',
  FATHER = 'padre',
  SON = 'hijo',
  DAUGHTER = 'hija',
  BROTHER = 'hermano',
  SISTER = 'hermana',
  GRANDMOTHER = 'abuela',
  GRANDFATHER = 'abuelo',
  GRANDSON = 'nieto',
  GRANDDAUGHTER = 'nieta',
  AUNT = 'tía',
  UNCLE = 'tío',
  COUSIN = 'primo/a',
  NEPHEW = 'sobrino',
  NIECE = 'sobrina',
  ME = 'yo',
}
